# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=30)),
                ('date', models.DateTimeField(verbose_name=b'date')),
                ('duration', models.DurationField(verbose_name=b'elapsed time')),
                ('distance', models.FloatField(verbose_name=b'distance')),
            ],
        ),
        migrations.CreateModel(
            name='TrkPt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DurationField(verbose_name=b'elapsed time')),
                ('lon', models.FloatField(verbose_name=b'longitude')),
                ('lat', models.FloatField(verbose_name=b'latitude')),
                ('ele', models.FloatField(verbose_name=b'elevation')),
                ('hr', models.PositiveSmallIntegerField(verbose_name=b'heart rate')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispact.Activity')),
            ],
        ),
    ]
